---
title: "Toolik salmon data"
format: html
editor: visual
execute: 
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---

## Toolik salmon biogeochemistry

```{r}
# load libraries
library(tidyverse)
library(here)
library(janitor)
```

```{r}
# read in the data
toolik_biochem <- read.csv("2011_Kling_Akchem.csv", na.strings = "NA") %>%
   clean_names()
toolik_biochem[toolik_biochem == "."] <- NA
toolik_biochem$site[toolik_biochem$site == "Toolik inlet"] <- "Toolik Inlet"
```

```{r}
inlet_biochem <- toolik_biochem %>% 
  filter(site == "Toolik Inlet") %>% 
  select(p_h, doc_u_m, tdn_u_m) %>% 
  mutate(across(everything(), as.numeric))
class(inlet_biochem$p_h)

# the slower way to do it
 # mutate(p_h = as.numeric(p_h), 
         # doc_u_m = as.numeric(doc_u_m), 
         # tdn_u_m = as.numeric(tdn_u_m))
```

```{r}
# mean way 1 with across 
mean_inlet <- inlet_biochem %>% 
  summarise(across(where(is.numeric), mean, na.rm = TRUE))
print(mean_inlet)

```

```{r}
# mean way 2 with apply
apply(inlet_biochem, 2, mean, na.rm = TRUE)
```

```{r}
# mean way 3 purrr version
map_df(.x = inlet_biochem, .f = mean, na.rm = TRUE)
```

```{r}
# mean way 4 for loop version
for (i in seq_along(inlet_biochem)) {
  mean_val <- mean(inlet_biochem[[i]], na.rm = TRUE)
  print(mean_val)
}
```
